# https://taskfile.dev

version: "3"

includes:
  public: https://raw.githubusercontent.com/fredrikaverpil/poc-tasks-nested/main/Taskfile.yml

tasks:
  poc-app:
    cmds:
      - go run github.com/fredrikaverpil/poc-tasks/cmd/app@latest
    silent: false
